name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo   # <-- tu app Next.js está en 'demo'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: demo/package-lock.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint (opcional)
        run: npm run lint --if-present

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          # Si tu build necesita variables, crea secrets y pásalas aquí.
          # EJ: NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npm run build

  backend:
    name: Backend (Gradle)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17   # usa 17 salvo que tu build.gradle pida 21

      - uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew (si existe)
        if: ${{ hashFiles('backend/gradlew') != '' }}
        run: chmod +x gradlew

      - name: Build con Gradle Wrapper
        if: ${{ hashFiles('backend/gradlew') != '' }}
        run: ./gradlew build --no-daemon

      - name: Build con Gradle (sin wrapper)
        if: ${{ hashFiles('backend/gradlew') == '' }}
        run: gradle build --no-daemon
